<a href="https://colab.research.google.com/github/jennyohyj/jennyohyj.github.io/blob/pandas%2Fnumpy-practice/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##데이터 연산

In [1]:
import pandas as pd
import numpy as np

In [2]:
s=pd.Series(np.random.randint(0,10,5))
s

0    4
1    7
2    6
3    7
4    2
dtype: int64

In [3]:
df=pd.DataFrame(np.random.randint(0,10,(3,3)),
                columns=['A','B','C'])
df

   A  B  C
0  2  2  4
1  5  4  1
2  2  2  5

In [4]:
np.exp(s)

0      54.598150
1    1096.633158
2     403.428793
3    1096.633158
4       7.389056
dtype: float64

In [5]:
np.cos(df*np.pi/4)

              A             B         C
0  6.123234e-17  6.123234e-17 -1.000000
1 -7.071068e-01 -1.000000e+00  0.707107
2  6.123234e-17  6.123234e-17 -0.707107

In [6]:
s1=pd.Series([1,3,5,7,9],index=[0,1,2,3,4,])
s2=pd.Series([2,4,6,8,10],index=[1,2,3,4,5])
s1+s2 ##동일한 index까지 더한다.

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [7]:
s1.add(s2,fill_value=0)  ##NAN대신에 0이 들어간다.

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [8]:
df1=pd.DataFrame(np.random.randint(0,20,(3,3)),
                 columns=list('ACD'))
df1

   A   C   D
0  0   1  10
1  8   2  19
2  6  14   1

In [9]:
df2=pd.DataFrame(np.random.randint(0,20,(5,5)),
                 columns=list('BAECD'))
df2

    B   A   E   C   D
0  11  17   4  19   4
1   5   4  11  10   5
2   9   5   2  10  11
3   1  10   1  19  16
4  15   8  18   8   8

In [10]:
df1+df2  ##비어 있는 곳이 많이 존재한다.

      A   B     C     D   E
0  17.0 NaN  20.0  14.0 NaN
1  12.0 NaN  12.0  24.0 NaN
2  11.0 NaN  24.0  12.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [11]:
fvalue=df1.stack().mean()
df1.add(df2,fill_value=fvalue)

           A          B          C          D          E
0  17.000000  17.777778  20.000000  14.000000  10.777778
1  12.000000  11.777778  12.000000  24.000000  17.777778
2  11.000000  15.777778  24.000000  12.000000   8.777778
3  16.777778   7.777778  25.777778  22.777778   7.777778
4  14.777778  21.777778  14.777778  14.777778  24.777778

In [12]:
a=np.random.randint(1,10,size=(3,3))
a

array([[6, 9, 3],
       [3, 6, 9],
       [9, 8, 7]])

In [ ]:
df=pd.DataFrame(a,columns=list('ABC'))
df

   A  B  C
0  4  5  7
1  4  6  3
2  5  1  5

In [ ]:
df+df.iloc[0]

   A   B   C
0  8  10  14
1  8  11  10
2  9   6  12

In [ ]:
df.add(df.iloc[0])

   A   B   C
0  8  10  14
1  8  11  10
2  9   6  12

In [ ]:
a-a[0]

array([[ 0,  0,  0],
       [ 0,  1, -4],
       [ 1, -4, -2]])

In [ ]:
df

   A  B  C
0  4  5  7
1  4  6  3
2  5  1  5

In [ ]:
df-df.iloc[0]

   A  B  C
0  0  0  0
1  0  1 -4
2  1 -4 -2

In [ ]:
df.sub(df.iloc[0])

   A  B  C
0  0  0  0
1  0  1 -4
2  1 -4 -2

In [ ]:
df.subtract(df['B'],axis=0)

   A  B  C
0 -1  0  2
1 -2  0 -3
2  4  0  4

In [ ]:
a

array([[4, 5, 7],
       [4, 6, 3],
       [5, 1, 5]])

In [ ]:
a*a[1]

array([[16, 30, 21],
       [16, 36,  9],
       [20,  6, 15]])

In [ ]:
df*df.iloc[1]

    A   B   C
0  16  30  21
1  16  36   9
2  20   6  15

In [ ]:
df.multiply(df.iloc[2])

    A  B   C
0  20  5  35
1  20  6  15
2  25  1  25

In [ ]:
a/a[0]

array([[1.        , 1.        , 1.        ],
       [1.        , 1.2       , 0.42857143],
       [1.25      , 0.2       , 0.71428571]])

In [ ]:
df/df.iloc[0]

      A    B         C
0  1.00  1.0  1.000000
1  1.00  1.2  0.428571
2  1.25  0.2  0.714286

In [ ]:
df.truediv(df.iloc[0])

      A    B         C
0  1.00  1.0  1.000000
1  1.00  1.2  0.428571
2  1.25  0.2  0.714286

In [ ]:
df.div(df.iloc[1])

      A         B         C
0  1.00  0.833333  2.333333
1  1.00  1.000000  1.000000
2  1.25  0.166667  1.666667

In [ ]:
df.divide(df.iloc[2])

     A    B    C
0  0.8  5.0  1.4
1  0.8  6.0  0.6
2  1.0  1.0  1.0

In [ ]:
a//a[0]

array([[1, 1, 1],
       [1, 1, 0],
       [1, 0, 0]])

In [ ]:
df.floordiv(df.iloc[0])

   A  B  C
0  1  1  1
1  1  1  0
2  1  0  0

In [ ]:
a%a[0]

array([[0, 0, 0],
       [0, 1, 3],
       [1, 1, 5]])

In [ ]:
df.mod(df.iloc[0]) ##나머지

   A  B  C
0  0  0  0
1  0  1  3
2  1  1  5

In [ ]:
a**a[0]

array([[   256,   3125, 823543],
       [   256,   7776,   2187],
       [   625,      1,  78125]])

In [ ]:
df.pow(df.iloc[0])

     A     B       C
0  256  3125  823543
1  256  7776    2187
2  625     1   78125

In [ ]:
row=df.iloc[0,::2]
row

A    4
C    7
Name: 0, dtype: int64

In [ ]:
df-row

     A   B    C
0  0.0 NaN  0.0
1  0.0 NaN -4.0
2  1.0 NaN -2.0

In [15]:
s=pd.Series(range(5),index=['A','D','B','C','E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [16]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [17]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [20]:
df=pd.DataFrame(np.random.randint(0,10,(4,4)),
                index=[2,4,1,3],
                columns=list('BDAC'))
df

   B  D  A  C
2  4  5  6  0
4  2  8  8  8
1  9  1  7  3
3  3  6  5  0

In [21]:
df.sort_index()

   B  D  A  C
1  9  1  7  3
2  4  5  6  0
3  3  6  5  0
4  2  8  8  8

In [22]:
df.sort_values(by='A')

   B  D  A  C
3  3  6  5  0
2  4  5  6  0
1  9  1  7  3
4  2  8  8  8

In [23]:
df.sort_values(by=['A','C'])

   B  D  A  C
3  3  6  5  0
2  4  5  6  0
1  9  1  7  3
4  2  8  8  8

In [24]:
df.sort_index(axis=1)

   A  B  C  D
2  6  4  0  5
4  8  2  8  8
1  7  9  3  1
3  5  3  0  6

In [26]:
s=pd.Series([-2,4,5,6,7,4,6,7])
s

0   -2
1    4
2    5
3    6
4    7
5    4
6    6
7    7
dtype: int64

In [27]:
s.rank()

0    1.0
1    2.5
2    4.0
3    5.5
4    7.5
5    2.5
6    5.5
7    7.5
dtype: float64

In [28]:
s.rank(method='first')

0    1.0
1    2.0
2    4.0
3    5.0
4    7.0
5    3.0
6    6.0
7    8.0
dtype: float64

In [29]:
s.rank(method='max')

0    1.0
1    3.0
2    4.0
3    6.0
4    8.0
5    3.0
6    6.0
7    8.0
dtype: float64

In [32]:
nrows,ncols=100000,100
df1, df2, df3, df4=(pd.DataFrame(np.random.rand(nrows,ncols)) for i in range(4))

In [33]:
%timeit df1+df2+df3+df4

10 loops, best of 5: 62.1 ms per loop

In [34]:
%timeit pd.eval('df1+df2+df3+df4')

10 loops, best of 5: 40.3 ms per loop

In [35]:
%timeit df1*-df2/(-df3*df4)

1 loop, best of 5: 113 ms per loop